// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
)

////go:embed HarmonyOS_Sans_SC_Light.ttf
//var ttf []byte

//var resourceGochiHandTtf = &fyne.StaticResource{
//	StaticName:    "GochiHand.ttf",
//	StaticContent:ttf}
